environment:
  my_salt:
    secure: pY+l2Pbf2Yyqifv2OGJtf6HlnYArlp1yITWhb8jr1cryjqujPMQaFe9kMwacFgH3Myv92kkq9Qtpk6DhFLHRNGrXOmD+ndHaCZ/NPJWiIIo=
  my_secret:
    secure: QMQlsox93ucriLcqZtErM7nwP9KflI+jJWk/kgYVSljmcgBuHcPXJr1+PoxZFCpFgXAMRL6xAFFFTNqqq4VVwg==
image: Ubuntu2004
install:
- mkdir -p /tmp/sensitive
- bash -x secure_file_setup.sh
- echo salt:$my_salt
- echo secret:$my_secret
- ./appveyor-tools/secure-file -decrypt ./auth.json.enc -secret "$my_secret" -salt "$my_salt" -out /tmp/sensitive/auth.json.decrypted
- cp /tmp/sensitive/auth.json.decrypted /run/user/0/containers/auth.json
- bash -x setup_debian.sh
- bash -x create_test.sh
test_script:
- bash test.sh
build: off
