environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor.monacelli@streambox.com
image: Ubuntu2004
install:
- bash -x secure_file_setup.sh
- ls -la ./auth.json.enc
# - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
# - sh: sleep 60m
- sh: ./appveyor-tools/secure-file -decrypt ./auth.json.enc -secret $my_secret -salt $my_salt -out /tmp/auth.json.decrypted
- sudo cp /tmp/auth.json.decrypted /run/user/0/containers/auth.json
- bash -x setup_debian.sh
- bash -x create_test.sh
test_script:
- bash test.sh
build: off
