environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor.monacelli@streambox.com
image: Ubuntu2004
install:
- bash -x secure_file_setup.sh
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- sh: ./appveyor-tools/secure-file -decrypt ./auth.json.enc -secret $my_secret -salt $my_salt -out /tmp/auth.json.decrypted
# https://ci.appveyor.com/project/TaylorMonacelli/mysql-replication-in-podman/builds/40699358
- sudo bash ./containers.sh 
- sudo bash setup_debian.sh >/dev/null
- sudo bash create_test.sh
- sudo git clone --depth 1 https://github.com/sstephenson/bats.git /tmp/bats; pushd /tmp/bats; sudo ./install.sh /usr/local; popd
test_script:
# - sudo bash -c 'source common.sh && cleanall'
- sudo bash test.sh
# - sudo bats test100.bats
# - sudo bats test200.bats
- sudo bats test_ensure_replication_is_running.bats
- sudo bats test_ensure_statement_based_binlog_format.bats
- sudo bats test_percona_checksums.bats
build: off
