environment:
  my_salt:
    secure: O4hKaZJ7JnJdk5Y+Z9ofQZsMy8wRjYAGnTmBtjiDr/A7QwdD9REJHWuE+SqFzvDdwfr69QlRw2B7OBD0ixRhm9dKZ4iiwd+VoAJpCxhGkQo=
  my_secret:
    secure: i3hzj1aGKbRsQHQkCw8C4huBICHF8qIFyBWb7Y08a/dKvtkrl+L7mcax24MaldT5Y7sHcADgoonYGePDY4tH2A==
image: Ubuntu2004
install:
- bash -x secure_file_setup.sh
- echo salt:$my_salt
- echo secret:$my_secret
- cat auth.json.enc
- ./appveyor-tools/secure-file -decrypt ./auth.json.enc -secret "$my_secret" -salt "$my_salt" -out /tmp/auth.json.decrypted
- cp /tmp/auth.json.decrypted /run/user/0/containers/auth.json
- bash -x setup_debian.sh
- bash -x create_test.sh
test_script:
- bash test.sh
build: off
