environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor.monacelli@streambox.com
image: Ubuntu2004
build: off
install:
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

# https://ci.appveyor.com/project/TaylorMonacelli/mysql-replication-in-podman/builds/40699358
- bash secure_file_setup.sh
- sh: ./appveyor-tools/secure-file -decrypt ./auth.json.enc -secret $my_secret -salt $my_salt -out /tmp/auth.json.decrypted

- sudo bash containers.sh >/dev/null
- sudo bash setup_debian.sh >/dev/null
- sudo bash create_setup.sh
- sudo podman info --debug

test_script:
- sudo time bash reset_containers.sh
- sudo time bash reset_data.sh

# - sudo time bats test_statement_based_binlog_format.bats
# - sudo time bats test_percona_checksums.bats
# - sudo time bats test_fart.bats
# - sudo time bats test_recover_from_bad_state.bats
